#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_version 2.0


if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
        # source dbconfig-common stuff
        . /usr/share/dbconfig-common/dpkg/config

        dbc_dbtypes=""
        for config in /usr/share/dbconfig-common/dpkg/config.*; do
            dbtype=$(basename "$config" | cut -d. -f2)
            dbc_dbtypes="$dbc_dbtypes, $dbtype"
        done
        dbc_dbtypes=$(echo "$dbc_dbtypes" | sed 's/^, //')
        dbc_authmethod_user="password"

        dbc_go cnb-cache "$@"


        # if [ -n "$dbc_dbtype" ]; then
        #         db_set cnb-cache/dbtype "$dbc_dbtype"
        #         echo "Setting dbtype to $dbc_dbtype"
        #         sleep 10
        # fi

fi
db_title Reconfigure webserever
db_input high cnb-cache/reconfigure-webserver || true

db_go || true
